### ISSUE TITLE
Use reserved port number

### ISSUE THREAD

**Issue by russellb** [metalkube/ironic-prometheus-exporter#7]
I noticed that the prometheus wiki has a page for reserving port numbers for various exporters.

https://github.com/prometheus/prometheus/wiki/Default-port-allocations

This page explains why it exists: https://prometheus.io/docs/instrumenting/writing_exporters/#port-numbers

I added a row to the table for the Ironic Prometheus Exporter.  Now the code should be updated to use the reserved port, `9608` by default.

**Comment by dtantsur** [comment]
Please open this bug in storyboard https://storyboard.openstack.org/#!/project/openstack/ironic-prometheus-exporter
